<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Build_Test_Dashboard.Test</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
    <PackageReference Include="ReportGenerator" Version="5.5.11" />
    <PackageReference Include="xunit.abstractions" Version="2.0.3" />
    <PackageReference Include="xunit.analyzers" Version="2.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" Version="4.0.0" />
    <PackageReference Include="xunit.v3.assert" Version="4.0.0" />
    <PackageReference Include="xunit.v3.common" Version="4.0.0" />
    <PackageReference Include="xunit.v3.core" Version="4.0.0" />
    <PackageReference Include="xunit.v3.core.mtp-off" Version="4.0.0" />
    <PackageReference Include="xunit.v3.core.mtp-v2" Version="4.0.0" />
    <PackageReference Include="xunit.v3.extensibility.core" Version="4.0.0" />
    <PackageReference Include="xunit.v3.mtp-off" Version="4.0.0" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="4.0.0" />
    <PackageReference Include="xunit.v3.runner.common" Version="4.0.0" />
    <PackageReference Include="xunit.v3.runner.inproc.console" Version="4.0.0" />
    <PackageReference Include="xunit.v3.runner.utility" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Build-Test-Dashboard\Build-Test-Dashboard.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>